/* Halo-style icons for the touch controls: original HUD-like shapes (bevelled
   bars, angular chevrons, a ring reticle, grenades, a magazine) drawn as
   vector paths on a 100-unit square and filled even-odd, so cut-outs read as
   holes. The paths use only absolute M, L, C and Z commands. They are
   generated by a script from the same data used to preview them; edit the
   shapes there rather than by hand. */
#import <UIKit/UIKit.h>
#import "host_touch.h"
#include <stdlib.h>
#include <string.h>

static const struct {
    const char *name;
    const char *path;
} halo_icons[]={
    {"reticle",
        "M86 50 C86 69.88 69.88 86 50 86 C30.12 86 14 69.88 14 50 C14 30.12 30.12 14 50 14 C69.88 14 86 "
        "30.12 86 50 Z M79 50 C79 66.02 66.02 79 50 79 C33.98 79 21 66.02 21 50 C21 33.98 33.98 21 50 21 "
        "C66.02 21 79 33.98 79 50 Z M46 8 L54 8 L52.5 26 L47.5 26 Z M92 46 L92 54 L74 52.5 L74 47.5 Z M54 "
        "92 L46 92 L47.5 74 L52.5 74 Z M8 54 L8 46 L26 47.5 L26 52.5 Z M55 50 C55 52.76 52.76 55 50 55 "
        "C47.24 55 45 52.76 45 50 C45 47.24 47.24 45 50 45 C52.76 45 55 47.24 55 50 Z"},
    {"bracket",
        "M22 14 L40 14 L40 21 L29 21 L29 32 L22 32 Z M86 22 L86 40 L79 40 L79 29 L68 29 L68 22 Z M78 86 "
        "L60 86 L60 79 L71 79 L71 68 L78 68 Z M14 78 L14 60 L21 60 L21 71 L32 71 L32 78 Z M50 38 L62 50 "
        "L50 62 L38 50 Z"},
    {"frag",
        "M71 60 C71 76.02 59.81 89 46 89 C32.19 89 21 76.02 21 60 C21 43.98 32.19 31 46 31 C59.81 31 71 "
        "43.98 71 60 Z M19 53 L73 53 L73 60 L19 60 Z M38 22 L54 22 L54 31 L38 31 Z M54 24 L72 24 L80 34 "
        "L80 60 L74 60 L74 37 L70 31 L54 31 Z"},
    {"plasma",
        "M67 52 C67 61.39 59.39 69 50 69 C40.61 69 33 61.39 33 52 C33 42.61 40.61 35 50 35 C59.39 35 67 "
        "42.61 67 52 Z M59 52 C59 56.97 54.97 61 50 61 C45.03 61 41 56.97 41 52 C41 47.03 45.03 43 50 43 "
        "C54.97 43 59 47.03 59 52 Z M60.94 21.93 L65.02 23.75 L68.81 26.11 L72.23 28.98 L75.22 32.3 "
        "L77.71 36 L79.67 40.01 L81.05 44.26 L81.82 48.66 L81.98 53.12 L81.51 57.56 L73.64 56.17 L73.99 "
        "52.84 L73.87 49.49 L73.29 46.19 L72.25 43.01 L70.78 40 L68.91 37.22 L66.67 34.74 L64.11 32.58 "
        "L61.27 30.81 L58.21 29.45 Z M70.57 76.51 L66.96 79.14 L63.02 81.23 L58.82 82.76 L54.45 83.69 L50 "
        "84 L45.55 83.69 L41.18 82.76 L36.98 81.23 L33.04 79.14 L29.43 76.51 L34.57 70.39 L37.28 72.35 "
        "L40.24 73.93 L43.38 75.07 L46.66 75.77 L50 76 L53.34 75.77 L56.62 75.07 L59.76 73.93 L62.72 "
        "72.35 L65.43 70.39 Z M18.49 57.56 L18.02 53.12 L18.18 48.66 L18.95 44.26 L20.33 40.01 L22.29 36 "
        "L24.78 32.3 L27.77 28.98 L31.19 26.11 L34.98 23.75 L39.06 21.93 L41.79 29.45 L38.73 30.81 L35.89 "
        "32.58 L33.33 34.74 L31.09 37.22 L29.22 40 L27.75 43.01 L26.71 46.19 L26.13 49.49 L26.01 52.84 "
        "L26.36 56.17 Z M41.54 27.42 L42.36 8.67 L49.55 26 Z M75.52 56.96 L91.35 67.05 L72.74 64.61 Z "
        "M32.94 71.62 L16.29 80.28 L27.71 65.39 Z"},
    {"impact",
        "M50 6 L57.65 31.52 L81.11 18.89 L74.02 40.05 L94 50 L68.48 57.65 L81.11 81.11 L59.95 74.02 L50 "
        "94 L42.35 68.48 L18.89 81.11 L25.98 59.95 L6 50 L31.52 42.35 L18.89 18.89 L40.05 25.98 Z"},
    {"jump",
        "M50 21 L81 40 L70 51 L50 33.65 L30 51 L19 40 Z M50 51 L81 70 L70 81 L50 63.65 L30 81 L19 70 Z"},
    {"crouch",
        "M50 55 L81 36 L70 25 L50 42.35 L30 25 L19 36 Z M21 70 L79 70 L82 73 L82 78 L79 81 L21 81 L18 78 "
        "L18 73 Z"},
    {"magazine",
        "M32 30 L62 30 L64 52 L74 86 L46 92 L36 56 Z M40.38 44 L64.62 44 L65.62 49 L41.38 49 Z M43.1 60 "
        "L69.9 60 L70.9 65 L44.1 65 Z M40 26 L40 16 L46 8 L52 16 L52 26 Z"},
    {"swap",
        "M14 34 L32 18 L32 28 L78 28 L78 40 L32 40 L32 50 Z M86 66 L68 82 L68 72 L22 72 L22 60 L68 60 L68 "
        "50 Z"},
    {"scope",
        "M88 50 C88 70.99 70.99 88 50 88 C29.01 88 12 70.99 12 50 C12 29.01 29.01 12 50 12 C70.99 12 88 "
        "29.01 88 50 Z M82 50 C82 67.67 67.67 82 50 82 C32.33 82 18 67.67 18 50 C18 32.33 32.33 18 50 18 "
        "C67.67 18 82 32.33 82 50 Z M47 16 L53 16 L53 42 L47 42 Z M47 58 L53 58 L53 84 L47 84 Z M16 47 "
        "L42 47 L42 53 L16 53 Z M58 47 L84 47 L84 53 L58 53 Z M29 50 C29 51.66 27.66 53 26 53 C24.34 53 "
        "23 51.66 23 50 C23 48.34 24.34 47 26 47 C27.66 47 29 48.34 29 50 Z M53 26 C53 27.66 51.66 29 50 "
        "29 C48.34 29 47 27.66 47 26 C47 24.34 48.34 23 50 23 C51.66 23 53 24.34 53 26 Z M77 50 C77 51.66 "
        "75.66 53 74 53 C72.34 53 71 51.66 71 50 C71 48.34 72.34 47 74 47 C75.66 47 77 48.34 77 50 Z M53 "
        "74 C53 75.66 51.66 77 50 77 C48.34 77 47 75.66 47 74 C47 72.34 48.34 71 50 71 C51.66 71 53 72.34 "
        "53 74 Z"},
    {"flashlight",
        "M18 70 L42 46 L52 56 L28 80 Z M42 46 L50 30 L70 50 L52 56 Z M62.4 27.8 L74.4 11.8 L69.6 8.2 "
        "L57.6 24.2 Z M70.95 38.85 L88.95 32.85 L87.05 27.15 L69.05 33.15 Z M59 22 L59 6 L53 6 L53 22 Z"},
    {"grenades",
        "M36.86 55.6 C36.86 66.17 29.47 74.74 20.36 74.74 C11.25 74.74 3.86 66.17 3.86 55.6 C3.86 45.03 "
        "11.25 36.46 20.36 36.46 C29.47 36.46 36.86 45.03 36.86 55.6 Z M2.54 50.98 L38.18 50.98 L38.18 "
        "55.6 L2.54 55.6 Z M15.08 30.52 L25.64 30.52 L25.64 36.46 L15.08 36.46 Z M25.64 31.84 L37.52 "
        "31.84 L42.8 38.44 L42.8 55.6 L38.84 55.6 L38.84 40.42 L36.2 36.46 L25.64 36.46 Z M77.54 52.24 "
        "C77.54 58.06 72.82 62.78 67 62.78 C61.18 62.78 56.46 58.06 56.46 52.24 C56.46 46.42 61.18 41.7 "
        "67 41.7 C72.82 41.7 77.54 46.42 77.54 52.24 Z M72.58 52.24 C72.58 55.32 70.08 57.82 67 57.82 "
        "C63.92 57.82 61.42 55.32 61.42 52.24 C61.42 49.16 63.92 46.66 67 46.66 C70.08 46.66 72.58 49.16 "
        "72.58 52.24 Z M73.79 33.6 L76.31 34.72 L78.66 36.19 L80.78 37.97 L82.63 40.03 L84.18 42.32 L85.4 "
        "44.81 L86.25 47.44 L86.73 50.17 L86.83 52.93 L86.54 55.69 L81.65 54.82 L81.87 52.76 L81.8 50.68 "
        "L81.44 48.64 L80.8 46.67 L79.89 44.8 L78.73 43.08 L77.34 41.54 L75.75 40.2 L73.99 39.1 L72.09 "
        "38.26 Z M79.75 67.44 L77.51 69.07 L75.07 70.36 L72.47 71.31 L69.76 71.89 L67 72.08 L64.24 71.89 "
        "L61.53 71.31 L58.93 70.36 L56.49 69.07 L54.25 67.44 L57.44 63.64 L59.11 64.86 L60.95 65.83 L62.9 "
        "66.54 L64.93 66.98 L67 67.12 L69.07 66.98 L71.1 66.54 L73.05 65.83 L74.89 64.86 L76.56 63.64 Z "
        "M47.46 55.69 L47.17 52.93 L47.27 50.17 L47.75 47.44 L48.6 44.81 L49.82 42.32 L51.37 40.03 L53.22 "
        "37.97 L55.34 36.19 L57.69 34.72 L60.21 33.6 L61.91 38.26 L60.01 39.1 L58.25 40.2 L56.66 41.54 "
        "L55.27 43.08 L54.11 44.8 L53.2 46.67 L52.56 48.64 L52.2 50.68 L52.13 52.76 L52.35 54.82 Z M61.75 "
        "37 L62.26 25.37 L66.72 36.12 Z M82.82 55.32 L92.63 61.57 L81.1 60.06 Z M56.42 64.41 L46.1 69.78 "
        "L53.18 60.54 Z"},
    {"pause",
        "M30 18 L39 18 L43 22 L43 78 L39 82 L30 82 L26 78 L26 22 Z M61 18 L70 18 L74 22 L74 78 L70 82 L61 "
        "82 L57 78 L57 22 Z"},
    {"scores",
        "M20 22 L80 22 L74 34 L14 34 Z M20 44 L80 44 L74 56 L14 56 Z M20 66 L80 66 L74 78 L14 78 Z"},
    {"arrow-up",
        "M50 18 L84 64 L62 64 L50 48 L38 64 L16 64 Z"},
    {"arrow-right",
        "M82 50 L36 84 L36 62 L52 50 L36 38 L36 16 Z"},
    {"arrow-down",
        "M50 82 L16 36 L38 36 L50 52 L62 36 L84 36 Z"},
    {"arrow-left",
        "M18 50 L64 16 L64 38 L48 50 L64 62 L64 84 Z"},
    {"start",
        "M30 16 L42 16 L80 46 L80 54 L42 84 L30 84 Z"},
};

static UIBezierPath *icon_path(const char *data, CGFloat scale) {
    UIBezierPath *path=[UIBezierPath bezierPath];
    path.usesEvenOddFillRule=YES;
    const char *cursor=data;
    char command=0;
    for(;;) {
        while(*cursor==' ' || *cursor==',') cursor++;
        if(!*cursor) break;
        if((*cursor>='A' && *cursor<='Z') || (*cursor>='a' && *cursor<='z')) {
            command=*cursor++;
            if(command=='Z') [path closePath];
            continue;
        }
        int count=command=='C'?6:(command=='M' || command=='L')?2:0;
        double value[6];
        if(!count) return path;
        for(int i=0;i<count;i++) {
            while(*cursor==' ' || *cursor==',') cursor++;
            char *end=NULL;
            value[i]=strtod(cursor,&end);
            if(end==cursor) return path;
            cursor=end;
        }
        if(command=='M') {
            [path moveToPoint:CGPointMake(value[0]*scale,value[1]*scale)];
            command='L';
        } else if(command=='L') {
            [path addLineToPoint:CGPointMake(value[0]*scale,value[1]*scale)];
        } else {
            [path addCurveToPoint:CGPointMake(value[4]*scale,value[5]*scale)
                controlPoint1:CGPointMake(value[0]*scale,value[1]*scale)
                controlPoint2:CGPointMake(value[2]*scale,value[3]*scale)];
        }
    }
    return path;
}

UIImage *halo_icon_image(NSString *name, CGFloat side) {
    const char *data=NULL;
    const char *wanted=name.UTF8String;
    if(!wanted || side<1) return nil;
    for(size_t i=0;i<sizeof(halo_icons)/sizeof(halo_icons[0]);i++)
        if(!strcmp(halo_icons[i].name,wanted)) {data=halo_icons[i].path;break;}
    if(!data) return nil;
    UIGraphicsImageRenderer *renderer=[[UIGraphicsImageRenderer alloc] initWithSize:CGSizeMake(side,side)];
    UIImage *image=[renderer imageWithActions:^(UIGraphicsImageRendererContext *context) {
        (void)context;
        [UIColor.whiteColor setFill];
        [icon_path(data,side/100.0) fill];
    }];
    return [image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
}
